/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ListOfPerceivedObjectContainer_H_
#define	_ListOfPerceivedObjectContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerceivedObjectContainer;

/* ListOfPerceivedObjectContainer */
typedef struct ListOfPerceivedObjectContainer {
	A_SEQUENCE_OF(struct PerceivedObjectContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListOfPerceivedObjectContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListOfPerceivedObjectContainer;
extern asn_SET_OF_specifics_t asn_SPC_ListOfPerceivedObjectContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ListOfPerceivedObjectContainer_1[1];
extern asn_per_constraints_t asn_PER_type_ListOfPerceivedObjectContainer_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerceivedObjectContainer.h"

#endif	/* _ListOfPerceivedObjectContainer_H_ */
#include "asn_internal.h"
