/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ListOfSensorInformationContainer_H_
#define	_ListOfSensorInformationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SensorInformationContainer;

/* ListOfSensorInformationContainer */
typedef struct ListOfSensorInformationContainer {
	A_SEQUENCE_OF(struct SensorInformationContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListOfSensorInformationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListOfSensorInformationContainer;
extern asn_SET_OF_specifics_t asn_SPC_ListOfSensorInformationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ListOfSensorInformationContainer_1[1];
extern asn_per_constraints_t asn_PER_type_ListOfSensorInformationContainer_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SensorInformationContainer.h"

#endif	/* _ListOfSensorInformationContainer_H_ */
#include "asn_internal.h"
