/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ListOfVehicleSensorProperties_H_
#define	_ListOfVehicleSensorProperties_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VehicleSensorProperties;

/* ListOfVehicleSensorProperties */
typedef struct ListOfVehicleSensorProperties {
	A_SEQUENCE_OF(struct VehicleSensorProperties) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListOfVehicleSensorProperties_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListOfVehicleSensorProperties;
extern asn_SET_OF_specifics_t asn_SPC_ListOfVehicleSensorProperties_specs_1;
extern asn_TYPE_member_t asn_MBR_ListOfVehicleSensorProperties_1[1];
extern asn_per_constraints_t asn_PER_type_ListOfVehicleSensorProperties_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleSensorProperties.h"

#endif	/* _ListOfVehicleSensorProperties_H_ */
#include "asn_internal.h"
