/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_Longit_H_
#define	_Longit_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Longit */
typedef long	 Longit_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Longit_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Longit;
asn_struct_free_f Longit_free;
asn_struct_print_f Longit_print;
asn_constr_check_f Longit_constraint;
ber_type_decoder_f Longit_decode_ber;
der_type_encoder_f Longit_encode_der;
xer_type_decoder_f Longit_decode_xer;
xer_type_encoder_f Longit_encode_xer;
oer_type_decoder_f Longit_decode_oer;
oer_type_encoder_f Longit_encode_oer;
per_type_decoder_f Longit_decode_uper;
per_type_encoder_f Longit_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Longit_H_ */
#include "asn_internal.h"
