/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PerceivedObjectContainer_H_
#define	_PerceivedObjectContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include <vanetza/asn1/its/StationID.h>
#include <vanetza/asn1/its/Identifier.h>
#include <vanetza/asn1/its/TimeOfMeasurement.h>
#include <vanetza/asn1/its/ObjectAge.h>
#include <vanetza/asn1/its/ObjectConfidence.h>
#include "Distance.h"
#include "SpeedExtended.h"
#include "ObjectRefPoint.h"
#include "DynamicStatus.h"
#include <vanetza/asn1/its/StationType.h>
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Distance;
struct SpeedExtended;
struct LongitudinalAcceleration;
struct LateralAcceleration;
struct VerticalAcceleration;
struct CartesianAngle;
struct ObjectDimension;
struct MatchedPosition;

/* PerceivedObjectContainer */
typedef struct PerceivedObjectContainer {
	StationID_t	 objectID;
	Identifier_t	*sensorID	/* OPTIONAL */;
	TimeOfMeasurement_t	 timeOfMeasurement;
	ObjectAge_t	*objectAge	/* OPTIONAL */;
	ObjectConfidence_t	*objectConfidence	/* OPTIONAL */;
	Distance_t	 xDistance;
	Distance_t	 yDistance;
	struct Distance	*zDistance	/* OPTIONAL */;
	SpeedExtended_t	 xSpeed;
	SpeedExtended_t	 ySpeed;
	struct SpeedExtended	*zSpeed	/* OPTIONAL */;
	struct LongitudinalAcceleration	*xAcceleration	/* OPTIONAL */;
	struct LateralAcceleration	*yAcceleration	/* OPTIONAL */;
	struct VerticalAcceleration	*zAcceleration	/* OPTIONAL */;
	struct CartesianAngle	*yawAngle	/* OPTIONAL */;
	struct ObjectDimension	*planarObjectDimension1	/* OPTIONAL */;
	struct ObjectDimension	*planarObjectDimension2	/* OPTIONAL */;
	struct ObjectDimension	*verticalObjectDimension	/* OPTIONAL */;
	ObjectRefPoint_t	 objectRefPoint	/* DEFAULT 0 */;
	DynamicStatus_t	*dynamicStatus	/* OPTIONAL */;
	StationType_t	*classification	/* OPTIONAL */;
	struct MatchedPosition	*matchedPosition	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_PerceivedObjectContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceivedObjectContainer_1[22];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Distance.h"
#include "SpeedExtended.h"
#include <vanetza/asn1/its/LongitudinalAcceleration.h>
#include <vanetza/asn1/its/LateralAcceleration.h>
#include <vanetza/asn1/its/VerticalAcceleration.h>
#include "CartesianAngle.h"
#include "ObjectDimension.h"
#include "MatchedPosition.h"

#endif	/* _PerceivedObjectContainer_H_ */
#include "asn_internal.h"
