/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SemiAxisLeng_H_
#define	_SemiAxisLeng_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemiAxisLeng {
	SemiAxisLeng_zeroPointOneMeter	= 1,
	SemiAxisLeng_oneMeter	= 10
} e_SemiAxisLeng;

/* SemiAxisLeng */
typedef long	 SemiAxisLeng_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SemiAxisLeng_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SemiAxisLeng;
asn_struct_free_f SemiAxisLeng_free;
asn_struct_print_f SemiAxisLeng_print;
asn_constr_check_f SemiAxisLeng_constraint;
ber_type_decoder_f SemiAxisLeng_decode_ber;
der_type_encoder_f SemiAxisLeng_encode_der;
xer_type_decoder_f SemiAxisLeng_decode_xer;
xer_type_encoder_f SemiAxisLeng_encode_xer;
oer_type_decoder_f SemiAxisLeng_decode_oer;
oer_type_encoder_f SemiAxisLeng_encode_oer;
per_type_decoder_f SemiAxisLeng_decode_uper;
per_type_encoder_f SemiAxisLeng_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SemiAxisLeng_H_ */
#include "asn_internal.h"
