/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SensorDetails.h"

static asn_oer_constraints_t asn_OER_type_SensorDetails_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SensorDetails_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SensorDetails_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.vehicleSensor),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VehicleSensor,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vehicleSensor"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.stationarySensorRadial),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationarySensorRadial,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationarySensorRadial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.stationarySensorPolygon),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationarySensorPolygon,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationarySensorPolygon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.stationarySensorCircular),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationarySensorCircular,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationarySensorCircular"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.stationarySensorEllipse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationarySensorEllipse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationarySensorEllipse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SensorDetails, choice.stationarySensorRectangle),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationarySensorRectangle,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationarySensorRectangle"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SensorDetails_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicleSensor */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* stationarySensorRadial */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* stationarySensorPolygon */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* stationarySensorCircular */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* stationarySensorEllipse */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* stationarySensorRectangle */
};
asn_CHOICE_specifics_t asn_SPC_SensorDetails_specs_1 = {
	sizeof(struct SensorDetails),
	offsetof(struct SensorDetails, _asn_ctx),
	offsetof(struct SensorDetails, present),
	sizeof(((struct SensorDetails *)0)->present),
	asn_MAP_SensorDetails_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SensorDetails = {
	"SensorDetails",
	"SensorDetails",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_SensorDetails_constr_1, &asn_PER_type_SensorDetails_constr_1, CHOICE_constraint },
	asn_MBR_SensorDetails_1,
	6,	/* Elements count */
	&asn_SPC_SensorDetails_specs_1	/* Additional specs */
};

