/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorDetails_H_
#define	_SensorDetails_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleSensor.h"
#include "StationarySensorRadial.h"
#include "StationarySensorPolygon.h"
#include "StationarySensorCircular.h"
#include "StationarySensorEllipse.h"
#include "StationarySensorRectangle.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SensorDetails_PR {
	SensorDetails_PR_NOTHING,	/* No components present */
	SensorDetails_PR_vehicleSensor,
	SensorDetails_PR_stationarySensorRadial,
	SensorDetails_PR_stationarySensorPolygon,
	SensorDetails_PR_stationarySensorCircular,
	SensorDetails_PR_stationarySensorEllipse,
	SensorDetails_PR_stationarySensorRectangle
	/* Extensions may appear below */
	
} SensorDetails_PR;

/* SensorDetails */
typedef struct SensorDetails {
	SensorDetails_PR present;
	union SensorDetails_u {
		VehicleSensor_t	 vehicleSensor;
		StationarySensorRadial_t	 stationarySensorRadial;
		StationarySensorPolygon_t	 stationarySensorPolygon;
		StationarySensorCircular_t	 stationarySensorCircular;
		StationarySensorEllipse_t	 stationarySensorEllipse;
		StationarySensorRectangle_t	 stationarySensorRectangle;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorDetails_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorDetails;
extern asn_CHOICE_specifics_t asn_SPC_SensorDetails_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorDetails_1[6];
extern asn_per_constraints_t asn_PER_type_SensorDetails_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorDetails_H_ */
#include "asn_internal.h"
