/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorInformationContainer_H_
#define	_SensorInformationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "SensorType.h"
#include "SensorDetails.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SensorInformationContainer */
typedef struct SensorInformationContainer {
	Identifier_t	 id;
	SensorType_t	 type;
	SensorDetails_t	 details;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorInformationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformationContainer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SensorInformationContainer_H_ */
#include "asn_internal.h"
