/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "StationarySensorRectangle.h"

asn_TYPE_member_t asn_MBR_StationarySensorRectangle_1[] = {
	{ ATF_POINTER, 1, offsetof(struct StationarySensorRectangle, nodeCenterPoint),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OffsetPoint,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodeCenterPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StationarySensorRectangle, semiMajorAxisLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiAxisLeng,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"semiMajorAxisLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StationarySensorRectangle, semiMinorAxisLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SemiAxisLeng,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"semiMinorAxisLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StationarySensorRectangle, semiMajorAxisOrientation),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WGS84AngleValue,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"semiMajorAxisOrientation"
		},
};
static const int asn_MAP_StationarySensorRectangle_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_StationarySensorRectangle_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StationarySensorRectangle_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodeCenterPoint */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* semiMajorAxisLength */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* semiMinorAxisLength */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* semiMajorAxisOrientation */
};
asn_SEQUENCE_specifics_t asn_SPC_StationarySensorRectangle_specs_1 = {
	sizeof(struct StationarySensorRectangle),
	offsetof(struct StationarySensorRectangle, _asn_ctx),
	asn_MAP_StationarySensorRectangle_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_StationarySensorRectangle_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StationarySensorRectangle = {
	"StationarySensorRectangle",
	"StationarySensorRectangle",
	&asn_OP_SEQUENCE,
	asn_DEF_StationarySensorRectangle_tags_1,
	sizeof(asn_DEF_StationarySensorRectangle_tags_1)
		/sizeof(asn_DEF_StationarySensorRectangle_tags_1[0]), /* 1 */
	asn_DEF_StationarySensorRectangle_tags_1,	/* Same as above */
	sizeof(asn_DEF_StationarySensorRectangle_tags_1)
		/sizeof(asn_DEF_StationarySensorRectangle_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StationarySensorRectangle_1,
	4,	/* Elements count */
	&asn_SPC_StationarySensorRectangle_specs_1	/* Additional specs */
};

