/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_StationarySensorEllipse_H_
#define	_StationarySensorEllipse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiAxisLeng.h"
#include "WGS84AngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* StationarySensorEllipse */
typedef struct StationarySensorEllipse {
	struct OffsetPoint	*nodeCenterPoint	/* OPTIONAL */;
	SemiAxisLeng_t	 semiMinorAxisLength;
	SemiAxisLeng_t	 semiMajorAxisLength;
	WGS84AngleValue_t	 semiMajorAxisOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationarySensorEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationarySensorEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_StationarySensorEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_StationarySensorEllipse_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _StationarySensorEllipse_H_ */
#include "asn_internal.h"
