/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "../cpm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_StationarySensorRectangle_H_
#define	_StationarySensorRectangle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SemiAxisLeng.h"
#include "WGS84AngleValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPoint;

/* StationarySensorRectangle */
typedef struct StationarySensorRectangle {
	struct OffsetPoint	*nodeCenterPoint	/* OPTIONAL */;
	SemiAxisLeng_t	 semiMajorAxisLength;
	SemiAxisLeng_t	 semiMinorAxisLength;
	WGS84AngleValue_t	 semiMajorAxisOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationarySensorRectangle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationarySensorRectangle;
extern asn_SEQUENCE_specifics_t asn_SPC_StationarySensorRectangle_specs_1;
extern asn_TYPE_member_t asn_MBR_StationarySensorRectangle_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPoint.h"

#endif	/* _StationarySensorRectangle_H_ */
#include "asn_internal.h"
